name: Update dataset

on:
  schedule:
    - cron: "00 00 * * *"
  workflow_dispatch:

jobs:
  build_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install curl
        run: |
          sudo apt install libcurl4-openssl-dev
      - name: Dependencies
        run: |
          Rscript -e "install.packages(c('dplyr','lubridate','rtweet'))"
      - name: Get data
        env:
          TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
          TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: |
          Rscript ./src/getData.R
      - name: Update repository
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/rstats_tweets.csv
          git commit -m "chore: Update tweet data" || echo "Failed on commit"
          git push || echo "Failed on push"
