# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  schedule:
    - cron: "00 00 * * 5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install curl
        run: |
          sudo apt install libcurl4-openssl-dev
      - name: Dependencies
        run: |
          Rscript -e "install.packages(c('dplyr','lubridate','rtweet'))"
      - name: Get data
        run: |
          Rscript ./src/getData.R
      - name: Update repository
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./data/rstats_tweets.csv
          git commit -m "chore: Update tweet data" || echo "Failed on commit"
          git push || echo "Failed on push"
